### ISSUE TITLE
Uncaught TypeError: code is not a function

### ISSUE THREAD

**Issue by emmreonal** [solidui/solid#447]
**Describe the bug**
**Console**
`Uncaught TypeError: code is not a function
    at bundle.js:341
    at bundle.js:38
    at runUpdates (bundle.js:210)
    at createRoot (bundle.js:38)
    at render (bundle.js:339)
    at bundle.js:464`

**bundle.js**
`function render(code, element, init) {
  let disposer;
  createRoot(dispose => {
    disposer = dispose;
    insert(element, code(), element.firstChild ? null : undefined, init);
  });
  return () => {
    disposer();
    element.textContent = "";
  };
}`

**index.jsx**
<code>
import { render } from "solid-js/web";
render(`<h1>Hello<h1>`, document.body);
</code>

**rollup.config.js**
<code>
import babel from "@rollup/plugin-babel";
import resolve from "@rollup/plugin-node-resolve";
import { terser } from "rollup-plugin-terser";

export default {
  input: "src/index.jsx",
  output: {
    file: "dist/bundle.js",
  },
  plugins: [
    babel({
      exclude: "node_modules/**",
      babelHelpers: "bundled",
      presets: ["solid"],
    }),
    resolve({ extensions: [".js", ".jsx"] }),
    !process.env.ROLLUP_WATCH && terser(),
  ],
};
</code>

**Comment by ryansolid** [comment]
The entry needs to wrapped in a function so it executes under a reactive context. https://github.com/solidui/solid/blob/main/documentation/rendering.md#entry

**Comment by emmreonal** [comment]
> The entry needs to wrapped in a function so it executes under a reactive context. https://github.com/solidui/solid/blob/main/documentation/rendering.md#entry

Problem solved.
